//
// Generated file, do not edit! Created by nedtool 4.6 from ExtMessage.msg.
//

#ifndef _EXTMESSAGE_M_H_
#define _EXTMESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "IPAddress.h"
// }}

/**
 * Class generated from <tt>ExtMessage.msg:22</tt> by nedtool.
 * <pre>
 * message ExtMessage
 * {
 *     IPAddress srcAddress;
 *     IPAddress dstAddress;
 *     int mask = 0;
 *     int hop = 0;
 * }
 * </pre>
 */
class ExtMessage : public ::cMessage
{
  protected:
    IPAddress srcAddress_var;
    IPAddress dstAddress_var;
    int mask_var;
    int hop_var;

  private:
    void copy(const ExtMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ExtMessage&);

  public:
    ExtMessage(const char *name=NULL, int kind=0);
    ExtMessage(const ExtMessage& other);
    virtual ~ExtMessage();
    ExtMessage& operator=(const ExtMessage& other);
    virtual ExtMessage *dup() const {return new ExtMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual IPAddress& getSrcAddress();
    virtual const IPAddress& getSrcAddress() const {return const_cast<ExtMessage*>(this)->getSrcAddress();}
    virtual void setSrcAddress(const IPAddress& srcAddress);
    virtual IPAddress& getDstAddress();
    virtual const IPAddress& getDstAddress() const {return const_cast<ExtMessage*>(this)->getDstAddress();}
    virtual void setDstAddress(const IPAddress& dstAddress);
    virtual int getMask() const;
    virtual void setMask(int mask);
    virtual int getHop() const;
    virtual void setHop(int hop);
};

inline void doPacking(cCommBuffer *b, ExtMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ExtMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _EXTMESSAGE_M_H_

